### PR TITLE
Add share path mapper with feature flag in the config

### PR DESCRIPTION
**Pull request by JarCz**
https://github.com/sciencemesh/cs3api4lab/issues/37 section 2

### CODE REVIEW

**Comment by diocas** [comment]
Please rebase a add some description of what is being done in the PR. It's a bit confusing to understand at first sight.

**Comment by JarCz** [comment]
Code in this PR cover the share path from IOP and transform into the normal relative path. If a user has the share path eg. "/reva/einsten/share_folder/share_test.txt" and on "Share by me" window click on the "/reva/ path can see other user data. (issue on IOP; https://github.com/cs3org/reva/issues/1390).  
The Mapping (share_mapper.py) creates an internal dictionary to store the original path and return to the frontend dictionary model with the mapped path. At reading containers or files it's executed the reverse process. If reading the path exists in a dictionary as the key it's replaced by the key-value and send to IOP instead of the path from the frontend.

**Comment by diocas** [comment]
I still don't fully understand. Are you trying to avoid users from being able to click in the path that is gerated to access a share?
And I don't understand what the bug you found has to do with our lab extension. Once this gets fixed there's no problem for us, right?

Also if the shares are supposed to be accessible via our "Share" tab, we shouldn't expose "/reva/<user>". We should only see there "Shares/<some share id>/". This way the user will only be able to return to the shares dialog and nowhere else. (I said from the begining that we will have to change the breadcrumb eventually.)

And I definetely don't understand why you are putting an in memory cache. This shouldn't be needed for anything as the mappings you need to do should be done based on the share id and nothing else (meaning that the mappings are static).

---
At some point in the future I want us to discuss exposing the full namespace (since is what we will be doing at CERN with CERNBox). Meaning that the user will start (home) in the path "/eos/user/d/diogo" and the shares might point to this path as well. So take that in consideration.

**Comment by JarCz** [comment]
I think we are able to freeze and close this PR now and will in the future, because:
- you are going to change the EOS names structure's
- yesterday presentation about changes in EOS 
- I spoke with Hugo on WP3 meet about this PR (https://github.com/cs3org/reva/issues/1390) and this bug should not have happened on a production system, because EOS watches over file access 

@diocas are you agree?

**Comment by diocas** [comment]
Fine by me. But keep in mind that this extension needs to work in deployments without EOS as well. But the access control to other files will for sure be imposed in wtv storage backend is used.

**Pull request closed without merging**
