### PR TITLE
Simple locking mechanism #11

### PR DESCRIPTION
**Pull request by mateusz-garlacz**
The idea is based on files metadata. The proposed flow is as follows:
- user creates a share with an original file
- the original file will contain in it's metadata information about locks i.e. who has a copy and if it is used or not
- when opening a file, check if it is a copy or original
- if you open a copy, the correspondent lock present in the original file's metadata will be updated
- if you open the original file, a copy and a lock will be created
- when closing a file, the endpoint deleting a lock should be invoked
- the contributor who has the merging rights would be the one who has the oldest and valid lock

Probably there are corrections to be done to cover some edge cases, but this is the idea in the nutshell. Please take a look and leave comments.

### CODE REVIEW

**Comment by diocas** [comment]
This is a long and complex PR, so I will need some time to review it. But can you give more details of the implementation? 
So, the lock information is only contained inside the file metadata? From a quick look, I got the impression that you kept some file(s) inside the user home dir? Why don't you create a hidden lock file, in the same directory and with its named based on the original file, just like the Office applications do?

**Comment by mateusz-garlacz** [comment]
Probably I introduced some unclarity because of naming.
Reva is the source of truth for the information about who has a copy of a given file and if someone is currently working on corresponding copy. The information is stored in the metadata. in this context I used 'copy' and 'lock' interchangeably. The Office-like 'lock file' you are reffering to would be something I call a copy. 

When opening a shared file, a copy is created (how to unable editing of the original file and switch the view to another tab from the frontend perspective is another topic). A possible improvements I can already see is the copy is now named with user-opaque-idp pattern but can be changed to '$originalName' like in Office.

**Comment by diocas** [comment]
@mateusz-garlacz I was going to review the PR again right now.. I guess you're going to replace it with something new? xD

**Comment by mateusz-garlacz** [comment]
Well... I decided that after so long time it needs some refreshment, so stay tuned :D

**Pull request closed without merging**
