### PR TITLE
fixed issues with strict null check

### PR DESCRIPTION
**Pull request by piotrWichlinskiSoftwaremind**

### CODE REVIEW

**Review by diocas — CHANGES_REQUESTED** [review]
Hey, can you please make the linting happy? Maybe there's an automated fix?
Otherwise we can merge this.
Thanks

**Comment by diocas** [comment]
@piotrWichlinskiSoftwaremind

**Comment by piotrWichlinskiSoftwaremind** [comment]
I've made the linter in the separate task which contains these changes, there are a lot of changes and I think it would be better to merge this piece by piece

**Comment by diocas** [comment]
I've sent you a message in Gitter. I'm replacing this PR with #92

**Pull request closed without merging**
