### PR TITLE
Apimanager refactor

### PR DESCRIPTION
**Pull request by dagl**
Remove duplicated code, refactor cs3apismanager

### CODE REVIEW

**Comment by dagl** [comment]
@diocas merge this after https://github.com/sciencemesh/cs3api4lab/pull/133

**Comment by dagl** [comment]
@diocas I corrected the errors

**Comment by diocas** [comment]
I'm waiting for the merger of #133 to review this once more.

**Comment by diocas** [comment]
@dagl can you please rebase?

**Review by diocas — APPROVED** [review]

**Pull request merged**
