### PR TITLE
Handle errors according to cs3 APIs

### PR DESCRIPTION
**Pull request by gmgigi96**
It improves the errors according to the ones specified into the APIs.

After this PR, will follow up an other regarding the locks as soon as they are implemented,

### CODE REVIEW

**Comment by dagl** [comment]
Hello, thanks for contributing. 

First of all please rebase. As it so happens, we also made some changes to error handling in shares, so there will be a conflict. 

Also 2 tests are not passing right now (TestCS3ApisManager - test_rename_file and one in TestCS3FileAPI). We try to have all tests green before merging (the exception are files test_cs3_ocm_share_api.py and test_cs3_public_share_api.py, we are still working on getting those fixed)

Lastly, would you mind writing new tests to reflect your changes? You can see an example in the changes I mentioned above. 
I'll take a more thorough look after rebasing.

**Review by dagl — CHANGES_REQUESTED** [review]
Hello, thanks for contributing.

First of all please rebase. As it so happens, we also made some changes to error handling in shares, so there will be a conflict.

Also 2 tests are not passing right now (TestCS3ApisManager - test_rename_file and one in TestCS3FileAPI). We try to have all tests green before merging (the exception are files test_cs3_ocm_share_api.py and test_cs3_public_share_api.py, we are still working on getting those fixed)

Lastly, would you mind writing new tests to reflect your changes? You can see an example in the changes I mentioned above.
I'll take a more thorough look after rebasing.

**Comment by diocas** [comment]
As we discussed yesterday, Aill will provide the tests to these changes.

**Comment by gmgigi96** [comment]
@dagl @diocas rebase done

**Comment by diocas** [comment]
As mentioned above, I'm merging this PR and will wait for a new one with the tests. ping @dagl

**Review by diocas — APPROVED** [review]

**Pull request merged**
